version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8090:8090
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    command: npm start